repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        stages: [pre-commit, pre-push]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        stages: [pre-commit, pre-push]

      - id: pytest
        name: pytest
        entry: pytest tests
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit, pre-push]
        always_run: true
